### ISSUE TITLE
Importing Real environment

### ISSUE THREAD

**Issue by Amit10311** [ZJU-FAST-Lab/am_traj#3]
Thank you for this great package for simulating MAV. I am running Ubuntu 16.04. The simulator is working perfectly. I want to set up my own environment. You have created the environment but I want to use the camera in the simulation and generate the octomap. I want to see the environment in the gazebo. Can you please guide me on how to set up the environment in your package.

I look forward to hearing from you. Thank you for your valuable time.

**Comment by ZhepeiWang** [comment]
To be honest, I am not familiar with gazebo... It is recommended that the camera render in our new work [EGO-Planner](https://github.com/ZJU-FAST-Lab/ego-planner/tree/master/src/uav_simulator/local_sensing) should be used. The camera render provides a CUDA-accelerated ray casting module in the simulation of this local planner. May it be helpful.
